### ISSUE TITLE
想了解怎么升级所使用的 Rspack 版本

### ISSUE THREAD

**Issue by AmbitionsXXXV** [noshower/electron-forge-plugin-rspack#1]
想了解怎么升级所使用的 Rspack 版本

**Comment by noshower** [comment]
之前 rspack 尚未稳定，因此包中的版本是写死的。 现在 rspack 1.0 发布， rspack 版本已调整为 ^ 的形式。

https://github.com/noshower/electron-forge-rspack-template  克隆这个仓库，可以体验下 rspack 1.0

**Comment by AmbitionsXXXV** [comment]
好的感谢😊
